//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoeshopMgt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("shoeshopMgt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap default_shoe_dealers_7 {
            get {
                object obj = ResourceManager.GetObject("default-shoe-dealers-7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20220309_WA0032 {
            get {
                object obj = ResourceManager.GetObject("IMG-20220309-WA0032", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20220316_WA0004___Copy {
            get {
                object obj = ResourceManager.GetObject("IMG-20220316-WA0004 - Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20220316_WA0005 {
            get {
                object obj = ResourceManager.GetObject("IMG-20220316-WA0005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20220316_WA0006 {
            get {
                object obj = ResourceManager.GetObject("IMG-20220316-WA0006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20220316_WA0009___Copy {
            get {
                object obj = ResourceManager.GetObject("IMG-20220316-WA0009 - Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20220316_WA0009___Copy1 {
            get {
                object obj = ResourceManager.GetObject("IMG-20220316-WA0009 - Copy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20220316_WA0010 {
            get {
                object obj = ResourceManager.GetObject("IMG-20220316-WA0010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20220316_WA0015 {
            get {
                object obj = ResourceManager.GetObject("IMG-20220316-WA0015", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20220316_WA0016 {
            get {
                object obj = ResourceManager.GetObject("IMG-20220316-WA0016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20220316_WA0021 {
            get {
                object obj = ResourceManager.GetObject("IMG-20220316-WA0021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20220316_WA0023 {
            get {
                object obj = ResourceManager.GetObject("IMG-20220316-WA0023", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20220316_WA00231 {
            get {
                object obj = ResourceManager.GetObject("IMG-20220316-WA00231", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20220316_WA0024 {
            get {
                object obj = ResourceManager.GetObject("IMG-20220316-WA0024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20220316_WA0025 {
            get {
                object obj = ResourceManager.GetObject("IMG-20220316-WA0025", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20220316_WA00251 {
            get {
                object obj = ResourceManager.GetObject("IMG-20220316-WA00251", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20220316_WA0032 {
            get {
                object obj = ResourceManager.GetObject("IMG-20220316-WA0032", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMG_20220316_WA0033 {
            get {
                object obj = ResourceManager.GetObject("IMG-20220316-WA0033", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
